name: Auto Cherry-Pick from Upstream

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to create the PR against"
        required: true
        default: "main"
      package_manager:
        description: "Specify package manager (npm or yarn)"
        required: false
        default: "yarn"
      script:
        description: "Specify a script to run after audit fix"
        required: false
        default: "yarn run all"
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  cherry-pick:
    if: github.event_name == 'workflow_dispatch' || contains(fromJson(toJson(github.event.pull_request.labels)).*.name, 'review-required')
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@v1
    with:
      original-owner: "crazy-max"
      repo-name: "ghaction-setup-docker"
      base_branch: ${{ inputs.base_branch }}
      package_manager: "yarn"
      script: ${{ inputs.script || 'yarn run all' }}
      mode: ${{ github.event_name == 'pull_request' && 'verify' || inputs.mode }}
